Rawasi/Rawasi/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('accounts/',include("accounts.urls")),
    path('investment_fund/',include("investment_fund.urls")),
    path('investments/', include("investments.urls"))
]  +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rawasi/investments/urls.py
from django.urls import path
from . import views

app_name = 'investments'

urlpatterns = [
    path('add_investment_opportunity/', views.add_investment_opportunity, name='add_investment_opportunity'),
    path('detail/<id>/', views.investment_opportunity_detail, name='investment_opportunity_detail'),
    path('investment_opportunity/delete/<id>/', views.delete_investment_opportunity, name='delete_investment_opportunity'),
    path('update/<id>/', views.update_investment_opportunity, name='update_investment_opportunity'),
    path('add-voting/', views.add_voting, name='add_voting'),
    path('opportunity-list/', views.opportunity_list, name='opportunity_list'),
    path('vote/<int:id>/', views.vote_on_opportunity, name='vote_on_opportunity'),
    path('buy_opportunity/<opportunity_id>/',views.buy_opportunity, name='buy_opportunity'),
    path('sell_opportunity/<opportunity_id>/',views.sell_opportunity, name='sell_opportunity'),
    path('vote/delete/<int:vote_id>/', views.delete_vote, name='delete_vote'),



]

Rawasi/main/urls.py
from . import views
from django.urls import path

app_name="main"

urlpatterns=[
    path('',views.home_view,name="home_view"),
    path('about/',views.about_view,name="about_view"),
    path('dashboard/fund/',views.fund_dashboard_view,name="fund_dashboard_view"),
    path('dashboard/investor/',views.investor_dashboard_view,name="investor_dashboard_view"),

]

Rawasi/investments/models.py
from django.db import models
from accounts.models import CustomUser, Investor
from investment_fund.models import InvestmentFund
from datetime import datetime
from decimal import Decimal
# Create your models here.

class InvestorFund(models.Model):
    fund = models.ForeignKey(InvestmentFund, on_delete=models.CASCADE, related_name='fund_investments') 
    investor = models.ForeignKey(Investor, on_delete=models.CASCADE, related_name='investments')  
    amount_invested = models.DecimalField(max_digits=12, decimal_places=2)
    invested_at = models.DateTimeField(auto_now_add=True)  
    status = models.CharField(max_length=100, choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending') 

    def calculate_profit(self):
        """Calculates profit based on associated opportunities and expected returns."""
        total_profit = Decimal(0.0)  # Use Decimal for precise calculations
        opportunities = self.fund.investment_opportunities.filter(status='Closed')  # Consider only closed opportunities
        
        for opportunity in opportunities:
            # Calculate the investment period (in days)
            invested_period_days = (opportunity.end_date - opportunity.start_date).days or 1
            # Calculate profit considering investment duration
            profit = self.amount_invested * (opportunity.expected_return / 100) * (invested_period_days / 365)  # Pro-rate the return over the investment duration
            total_profit += profit
        
        # Optionally update the status after calculating the profit
        if total_profit > 0:
            self.status = 'Completed'
            self.save()

        return round(total_profit, 2)  # Return profit rounded to 2 decimal places


class InvestmentOpportunity(models.Model):
    INVESTMENT_TYPE_CHOICES = [
        ('Stocks', 'Stocks'),
        ('Real Estate', 'Real Estate')
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    company_name = models.CharField(max_length=255)
    fund = models.ForeignKey(InvestmentFund, on_delete=models.CASCADE, related_name='investment_opportunities') 
    investment_type = models.CharField(max_length=100, choices=INVESTMENT_TYPE_CHOICES, blank=False, null=False)
    total_investment = models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    expected_return = models.FloatField()
    status = models.CharField(max_length=100, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Completed', 'Completed')], default='Open')
    pdf_file = models.FileField(upload_to='investment_opportunities/pdf/', blank=True, null=True)
    image = models.ImageField(upload_to='investment_opportunities/images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.title
    


class Voting(models.Model):
    APPROVAL_CHOICES = [
        ('Accepted', 'Accepted'), 
        ('Rejected', 'Rejected'),
        ('Pending', 'Pending') ,
    ]
    VOTE_TYPE_CHOICES = [
        ('Buy', 'Buy'),
        ('Sell', 'Sell'),
    ]
    opportunity = models.ForeignKey('InvestmentOpportunity', on_delete=models.CASCADE, related_name='votes')  
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE) 
    vote = models.CharField(max_length=10, choices=APPROVAL_CHOICES, default='Pending') 
    vote_type = models.CharField(max_length=4, choices=VOTE_TYPE_CHOICES, default='Buy')
    required_approval_percentage = models.FloatField(default=70.0)  
    voting_start_time = models.DateTimeField(default=datetime.now)
    voting_end_time = models.DateTimeField(default=datetime.now)
    total_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} voted {self.vote} on {self.opportunity.title}"

class BuySellTransaction(models.Model):
    TRANSACTION_TYPE_CHOICES = [
        ('Buy', 'Buy'),
        ('Sell', 'Sell'), 
    ]
    
    opportunity = models.ForeignKey(InvestmentOpportunity, on_delete=models.CASCADE, related_name='buy_sell_transactions') 
    transaction_type = models.CharField(max_length=4, choices=TRANSACTION_TYPE_CHOICES) 
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_date = models.DateTimeField(auto_now_add=True) 
    status = models.CharField(max_length=50, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')],default='Pending') 

    def __str__(self):
        return f"{self.get_transaction_type_display()} Transaction for {self.opportunity.title}"

    

Rawasi/investments/forms.py
from django import forms
from .models import InvestmentOpportunity , Voting

class InvestmentOpportunityForm(forms.ModelForm):
    class Meta:
        model = InvestmentOpportunity
        fields = ['title', 'description', 'investment_type', 'total_investment', 'start_date', 'end_date', 'image', 'pdf_file']

class VotingForm(forms.ModelForm):
    voting_duration_days = forms.IntegerField(
        min_value=1, 
        label="Voting Duration (in days)", 
        widget=forms.NumberInput(attrs={'placeholder': 'Duration in days'})
    )
    
    required_approval_percentage = forms.FloatField(
        min_value=0, 
        max_value=100, 
        label="Required Approval Percentage",
        widget=forms.NumberInput(attrs={'placeholder': 'Approval percentage'})
    )

    vote_type = forms.ChoiceField(
        choices=Voting.VOTE_TYPE_CHOICES,  
        label="Vote Type",
        widget=forms.Select(attrs={'placeholder': 'Select Vote Type'})
    )

    class Meta:
        model = Voting
        fields = ['vote_type', 'required_approval_percentage', 'voting_duration_days']  

    

Rawasi/investments/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import InvestmentOpportunity
from investment_fund.models import InvestmentFund
from accounts.models import Leader
from django.contrib import messages
from investments.forms import InvestmentOpportunityForm
from datetime import datetime
from .models import InvestorFund, Voting , BuySellTransaction
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, HttpResponse
from decimal import Decimal
from datetime import timedelta
from django.utils import timezone


# Create your views here.

@login_required
def add_investment_opportunity(request):
    leader = Leader.objects.filter(user=request.user).first()
    active_section = 'section4' 



    if not leader:
        messages.error(request, "فقط المسؤول يمكنه إضافة فرص استثمارية.")
        return redirect('dashboard:fund_dashboard_view') 

    if request.method == "POST":
        
        title = request.POST.get('title')
        description = request.POST.get('description')
        company_name = request.POST.get('company_name')
        investment_type = request.POST.get('investment_type')
        total_investment = request.POST.get('total_investment')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        expected_return = request.POST.get('expected_return')
        pdf_file = request.FILES.get('pdf_file')
        image = request.FILES.get('image')

        if not all([title, description, company_name, investment_type, total_investment, start_date, end_date, expected_return]):
            messages.error(request, "جميع الحقول مطلوبة.")
            return redirect(f'/dashboard/fund/?section={active_section}')

        fund = leader.managed_fund
        print(fund.is_active)
        if not fund:
            messages.error(request, "لا يوجد صندوق استثماري في النظام. يرجى إضافة صندوق استثماري أولاً.")
            return redirect(f'/dashboard/fund/?section={active_section}')

        '''if fund.leader != leader:
            messages.error(request, "لا يمكنك إضافة فرصة استثمارية لأنك لست المسؤول عن هذا الصندوق.")
            return redirect(f'/dashboard/fund/?section={active_section}')'''

        if fund.is_active != 'Active':
            messages.error(request, "لا يمكن إضافة فرص استثمارية لأن الصندوق غير نشط.")
            return redirect(f'/dashboard/fund/?section={active_section}')

        try:
            start_date = datetime.strptime(start_date, '%Y-%m-%d')
            end_date = datetime.strptime(end_date, '%Y-%m-%d')
            if start_date >= end_date:
                messages.error(request, "تاريخ البدء يجب أن يكون قبل تاريخ الانتهاء.")
                return redirect(f'/dashboard/fund/?section={active_section}')
        except ValueError:
            messages.error(request, "تاريخ البدء والانتهاء غير صحيح.")
            return redirect(f'/dashboard/fund/?section={active_section}')

        investment_opportunity = InvestmentOpportunity(
            title=title,
            description=description,
            company_name=company_name,
            investment_type=investment_type,
            total_investment=total_investment,
            start_date=start_date,
            end_date=end_date,
            expected_return=expected_return,
            fund=fund,
            pdf_file=pdf_file,
            image=image,
        )

        try:
            investment_opportunity.save()
            messages.success(request, "تم إضافة الفرصة الاستثمارية بنجاح!")
            return redirect(f'/dashboard/fund/?section={active_section}')
        except Exception as e:
            messages.error(request, f"حدث خطأ أثناء إضافة الفرصة الاستثمارية: {str(e)}")
            return redirect(f'/dashboard/fund/?section={active_section}')



    return render(request, 'investments/add_investment_opportunity.html')


@login_required
def investment_opportunity_detail(request, id):

    investment_opportunity = get_object_or_404(InvestmentOpportunity, id=id)
    
    fund = investment_opportunity.fund
    is_leader = hasattr(request.user, 'leader') and request.user.leader.managed_fund == fund
    is_investor = InvestorFund.objects.filter(investor__user=request.user, fund=fund).exists()
    total_votes = investment_opportunity.votes.count()
    accepted_votes = investment_opportunity.votes.filter(vote='Accepted').count()

    if total_votes > 0:
        approval_percentage = (accepted_votes / total_votes) * 100
    else:
        approval_percentage = 0  

    buy_votes_accepted = investment_opportunity.votes.filter(vote_type='Buy', vote='Accepted').count()
    sell_votes_accepted = investment_opportunity.votes.filter(vote_type='Sell', vote='Accepted').count()
    total_investors = InvestorFund.objects.filter(fund=fund).count()

    approval_percentage_buy = (buy_votes_accepted / total_investors) * 100 if total_investors else 0
    approval_percentage_sell = (sell_votes_accepted / total_investors) * 100 if total_investors else 0
    


    user_vote = None
    if request.user.is_authenticated:
        user_vote = investment_opportunity.votes.filter(user=request.user).first()


    if not is_leader and not is_investor:
        messages.error(request, "ليس لديك صلاحية للوصول إلى تفاصيل هذه الفرصة الاستثمارية.")
        return redirect('/')
    # calculates days
    left_days = (investment_opportunity.end_date - investment_opportunity.start_date).days

    
    

    return render(request, 'investments/investment_opportunity_detail.html', {
        'investment_opportunity': investment_opportunity,
        'approval_percentage': approval_percentage,
        'user_vote': user_vote,
        "left_days":left_days,
    })

@login_required
def delete_investment_opportunity(request, id):
    investment_opportunity = get_object_or_404(InvestmentOpportunity, id=id)

    leader = Leader.objects.filter(user=request.user).first()
    
    if not leader:
        messages.error(request, "ليس لديك صلاحية لحذف هذه الفرصة الاستثمارية.")
        return redirect('/')

    if investment_opportunity.fund.leader != leader:
        messages.error(request, "لا يمكنك حذف هذه الفرصة الاستثمارية لأنك لست المسؤول عن هذا الصندوق.")
        return redirect('/')

    investment_opportunity.delete()

    messages.success(request, "تم حذف الفرصة الاستثمارية بنجاح.")
    return redirect('/')

@login_required
def update_investment_opportunity(request, id):
    investment_opportunity = get_object_or_404(InvestmentOpportunity, id=id)
    
    leader = Leader.objects.filter(user=request.user).first()
    
    if not leader:
        messages.error(request, "ليس لديك صلاحية لتحديث هذه الفرصة الاستثمارية.")
        return redirect('/') 

    if investment_opportunity.fund.leader != leader:
        messages.error(request, "لا يمكنك تحديث هذه الفرصة الاستثمارية لأنك لست المسؤول عن هذا الصندوق.")
        return redirect('/')  
    try:
        voting_start_time = datetime.strptime(voting_start_time, '%Y-%m-%d')
        voting_end_time = datetime.strptime(voting_end_time, '%Y-%m-%d')
        if voting_start_time >= voting_end_time:
         messages.error(request, "تاريخ البدء يجب أن يكون قبل تاريخ الانتهاء.")
    except ValueError:
         messages.error(request, "تاريخ البدء والانتهاء غير صحيح.")
    
    if request.method == 'POST':
        form = InvestmentOpportunityForm(request.POST, request.FILES, instance=investment_opportunity)
        if form.is_valid():
            form.save()
            messages.success(request, "تم تعديل الفرصة الاستثمارية بنجاح.")
            return redirect('investments:investment_opportunity_detail', id=investment_opportunity.id)
    else:
        form = InvestmentOpportunityForm(instance=investment_opportunity)
    
    return render(request, 'investments/update_investment_opportunity.html', {'form': form})


@login_required
def add_voting(request):
    active_section = 'section2' 
    try:
        leader = request.user.leader 
        fund = leader.managed_fund
    except Leader.DoesNotExist:
        fund = None
    if not fund:
        raise PermissionDenied("ليس لديك صلاحية للوصول إلى هذا الصندوق الاستثماري.")
    
    '''try:
            investor_fund = InvestorFund.objects.get(investor__user=request.user, fund=fund)
        except InvestorFund.DoesNotExist:
            messages.error(request, "لم تقم بالاستثمار في هذا الصندوق بعد. لا يمكنك التصويت.")
            return redirect('investments:opportunity_list')'''

    if request.method == "POST":
        opportunity_id = request.POST.get('opportunity')
        required_approval_percentage = float(request.POST.get('required_approval_percentage'))
        voting_start_time = request.POST.get('voting_start_time')
        voting_end_time = request.POST.get('voting_end_time')
        total_amount = request.POST.get('total_amount')
        vote_type = 'Buy'

        try:
            opportunity = InvestmentOpportunity.objects.get(id=opportunity_id)
            
            if opportunity.fund != fund:
                raise PermissionDenied("ليس لديك صلاحية لوضع تصويت على هذه الفرصة الاستثمارية.")

            if Voting.objects.filter(opportunity=opportunity, vote_type='Sell', vote='Accepted').exists():
                messages.error(request, "تمت الموافقة على تصويت البيع لهذه الفرصة. لا يمكن إضافة تصويت جديد للبيع.")
                return redirect('investments:add_voting')
            
            voting = Voting(
                opportunity=opportunity,
                user=request.user,
                required_approval_percentage=required_approval_percentage,
                voting_start_time=voting_start_time,
                voting_end_time=voting_end_time,
                total_amount=total_amount,
                vote_type=vote_type, 
            )
            voting.save()
            print(f"قبل إضافة التصويت، حالة الفرصة: {opportunity.status}")

            print(f"فرصة الاستثمار: {opportunity}")

Rawasi/investments/templates/investments/add_investment_opportunity.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
<link href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
<style>
    .modal-content {
        border-radius: 15px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    }

    .modal-dialog {
        max-width: 900px; 
    }

    .modal-header {
        background-color: #761305;
        color: white;
        font-weight: bold;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        padding-left: 60px; 
    }

    .modal-header .btn-close {
        position: absolute;
        left: 10px;
        top: 20px;
        background-color: #761305;
        border-radius: 50%;
    }

    .modal-footer {
        border-bottom-left-radius: 10px;
        border-bottom-right-radius: 10px;
    }

    .form-control, .form-select {
        border-radius: 8px;
        border: 1px solid #ddd;
        transition: border-color 0.3s ease;
    }

    .form-control:focus, .form-select:focus {
        border-color: #761305;
        box-shadow: 0 0 5px rgba(118, 19, 5, 0.5);
    }

    .btn-darkgreen {
        background-color: #3b6e4e;
        border-color: #3b6e4e;
        transition: background-color 0.3s ease;
    }

    .btn-darkgreen:hover {
        background-color: #2a4a35;
        border-color: #2a4a35;
    }

    .btn-close {
        background-color: #761305;
        border-radius: 50%;
    }

    .modal-footer .btn-secondary {
        background-color: #ccc;
        border-color: #ccc;
        border-radius: 8px;
    }

    .modal-footer .btn-secondary:hover {
        background-color: #aaa;
        border-color: #aaa;
    }

    .modal-body {
        padding: 30px;
    }
</style>
{% endblock %}

{% block title %}
<title>فرصة استثمارية جديدة</title>
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card p-4 shadow-lg" style="max-width: 700px; width: 100%; margin-top: 5%; border-radius: 15px;">
        {% if messages %}
          {% for message in messages %}
          {% if not request.session.show_message or message.tags != request.session.show_message %}
              <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
                  {{ message }}
              </div>
              {% endif %}
          {% endfor %}
        {% endif %}
        <h2 class="text-center mb-4" style="color: #761305;">إضافة فرصة استثمارية</h2>

        <button type="button" class="btn btn-darkgreen w-100" data-bs-toggle="modal" data-bs-target="#investmentOpportunityModal">
            إضافة فرصة استثمارية جديدة
        </button>

        <div class="modal fade" id="investmentOpportunityModal" tabindex="-1" aria-labelledby="investmentOpportunityModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="investmentOpportunityModalLabel">إضافة فرصة استثمارية جديدة</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST"  enctype="multipart/form-data">
                            {% csrf_token %}
                        
                            <div class="mb-3">
                                <label for="title" class="form-label" style="color: #761305;">عنوان الاستثمار</label>
                                <input type="text" class="form-control" id="title" name="title" required>
                            </div>

                            <div class="mb-3">
                                <label for="description" class="form-label" style="color: #761305;">وصف الاستثمار</label>
                                <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
                            </div>

                            <div class="mb-3">
                                <label for="company_name" class="form-label" style="color: #761305;">اسم الشركة</label>
                                <input type="text" class="form-control" id="company_name" name="company_name" required>
                            </div>

                            <div class="mb-3">
                                <label for="investment_type" class="form-label" style="color: #761305;">نوع الاستثمار</label>
                                <select class="form-select" id="investment_type" name="investment_type" required>
                                    <option value="Stocks">أسهم</option>
                                    <option value="Real Estate">عقارات</option>
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="total_investment" class="form-label" style="color: #761305;">المبلغ الإجمالي للاستثمار</label>
                                <input type="number" class="form-control" id="total_investment" name="total_investment" required>
                            </div>                          

                            <div class="mb-3">
                                <label for="start_date" class="form-label" style="color: #761305;">تاريخ البداية</label>
                                <input type="date" class="form-control" id="start_date" name="start_date" required>
                            </div>

                            <div class="mb-3">
                                <label for="end_date" class="form-label" style="color: #761305;">تاريخ الانتهاء</label>
                                <input type="date" class="form-control" id="end_date" name="end_date" required>
                            </div>

                            <div class="mb-3">
                                <label for="expected_return" class="form-label" style="color: #761305;">العائد المتوقع</label>
                                <input type="number" class="form-control" id="expected_return" name="expected_return" required>
                            </div>
                            <div class="mb-3">
                                <label for="investment_image" class="form-label" style="color: #761305;">صورة الاستثمار</label>
                                <input type="file" class="form-control" id="investment_image" name="investment_image" accept="image/*">
                            </div>

                            <div class="mb-3">
                                <label for="investment_pdf" class="form-label" style="color: #761305;">تحميل ملف PDF</label>
                                <input type="file" class="form-control" id="investment_pdf" name="investment_pdf" accept="application/pdf">
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
                                <button type="submit" class="btn btn-darkgreen">إضافة الفرصة</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

Rawasi/investments/templates/investments/opportunity_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <h2 class="text-center mb-4" style="color: #761305;">الفرص الاستثمارية المتاحة</h2>
    {% if messages %}
    {% for message in messages %}
    {% if not request.session.show_message or message.tags != request.session.show_message %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
    {% endif %}

    <div class="row">
        {% for opportunity in opportunities %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title" style="color: #761305;">{{ opportunity.title }}</h5>
                <p class="card-text"><strong>المبلغ الإجمالي:</strong> {{ opportunity.total_investment }} ريال</p>
                <p class="card-text"><strong>العائد المتوقع:</strong> {{ opportunity.expected_return }}%</p>
                <p class="card-text"><strong>تاريخ البداية:</strong> {{ opportunity.start_date|date:"Y-m-d" }}</p>
                <p class="card-text"><strong>تاريخ الانتهاء:</strong> {{ opportunity.end_date|date:"Y-m-d" }}</p>
                <p class="card-text"><strong>النسبة المطلوبة للموافقة:</strong> {{ opportunity.required_approval_percentage }}%</p>
                <p class="card-text"><strong>نسبة الموافقه:</strong> {{ opportunity.approval_percentage }}%</p>
                <p class="card-text"><strong>قبول :</strong> {{ opportunity.accepted_votes }}</p>
                <p class="card-text"><strong>رفض :</strong> {{ opportunity.rejected_votes }}</p>

                <p class="card-text">
                    {% if opportunity.status == 'Closed' %}
                        <span class="badge bg-dark">تم إغلاق التصويت</span>
                    {% elif opportunity.status == 'Open' %}
                        {% if opportunity.pending_votes > 0 %}
                            <span class="badge bg-warning">التصويت قيد الانتظار</span>
                        {% else %}
                            <span class="badge bg-success">التصويت مكتمل</span>
                        {% endif %}
                    {% elif opportunity.status == 'Not Started' %}
                        <span class="badge bg-secondary">لم يتم بدء التصويت</span> 
                    {% endif %}
                </p>

                <div class="d-flex justify-content-between">
                    <a href="{% url 'investments:investment_opportunity_detail' id=opportunity.id %}" class="btn btn-darkgreen">تفاصيل الفرصة</a>

                    {% if opportunity.status == 'Open' %}
                        <form method="POST" action="{% url 'investments:vote_on_opportunity' id=opportunity.id %}">
                            {% csrf_token %}
                            <button type="submit" name="vote_choice" value="Accepted" class="btn btn-success">أوافق</button>
                            <button type="submit" name="vote_choice" value="Rejected" class="btn btn-danger">أرفض</button>
                        </form>
                    {% elif opportunity.status == 'Closed' %}
                    {% if opportunity.status == 'Closed' and request.user == opportunity.fund.leader.user %}
                    <form method="POST">
                        {% csrf_token %}
                        
                        <label for="new_start_time" class="form-label" style="color: #761305;">تاريخ بداية التصويت الجديد</label>
                        <input type="datetime-local" class="form-control" id="new_start_time" name="new_start_time" value="{{ opportunity.start_date|date:'Y-m-d\TH:i' }}" required>
                
                        <label for="new_end_time" class="form-label" style="color: #761305;">تاريخ نهاية التصويت الجديد</label>
                        <input type="datetime-local" class="form-control" id="new_end_time" name="new_end_time" value="{{ opportunity.end_date|date:'Y-m-d\TH:i' }}" required>
                
                        <button type="submit" name="reopen_vote" class="btn btn-warning">إعادة فتح التصويت</button>
                    </form>
                {% endif %}
                
                    
                    
                        <span class="badge bg-dark">تم إغلاق التصويت</span>
                    {% endif %}

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}